controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: fr|en

app_logout:
    path: /logout
    methods: GET
    
site_home:
    path:  /
    controller: App\Controller\DefaultController::index

